### ISSUE TITLE
Missing Classes Problem

### ISSUE THREAD

**Issue by PragueSquare** [JavierMF/features-service#11]
Hello! I downloaded and was to run the codes, but I found that the Dao classes were wrong. Because there are some classes missing in the Model package, as shown in the following figure. Did you miss some classes that had not been uploaded? 
![problem](https://user-images.githubusercontent.com/38074845/40873965-efb456ac-6658-11e8-9871-446eed6a8e2c.png)

**Comment by JavierMF** [comment]
Hello!
Those classes are automatically generate when packaging the project using maven. They are managed by QueryDSL (http://www.querydsl.com/). Please, try execute "mvn package" and they will be generated for you.
Thank you.
